# Generated by Django 4.1.9 on 2023-08-25 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('movie_length', models.IntegerField()),
                ('loction', models.CharField(max_length=255)),
                ('total_seats', models.PositiveIntegerField()),
                ('image', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('is_resvered', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=40)),
                ('movie_timeing', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_app.movies')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theatre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_app.theatre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_app.movies')),
                ('seat_number', models.ManyToManyField(to='Movie_app.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='Theatre_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_app.theatre'),
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_app.movies'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(default=0.0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_app.movies')),
                ('seat_number', models.ManyToManyField(to='Movie_app.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
