# Generated by Django 4.1.9 on 2023-08-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_resvered',
            new_name='is_reserved',
        ),
    ]
